Repository galacean/engine-toolkit, pull requests merged in 2022-08, with the labels that each got.

#45 Fix/lines init
  packages/lines/src/line/DashLine.ts
  packages/lines/src/line/Line.ts
  packages/lines/src/line/vertexBuilder/atob.ts
  packages/lines/src/line/vertexBuilder/index.ts
Labels: bug, ignore for release

#46 Fix WireFrame local position and upAxis bug
  packages/auxiliary-lines/src/WireframeManager.ts
Labels: bug

#47 fix: camera NDC z bug
  packages/auxiliary-lines/src/WireframeManager.ts
Labels: bug

#48 Fix outline transform error
  packages/outline/src/OutlineManager.ts
Labels: bug

#51 fix outline wrap mode error
  packages/outline/src/OutlineManager.ts
Labels: bug

#60 Optimization outline
  packages/outline/src/OutlineManager.ts
Labels: enhancement

#61 refactor outline with `layer` and main/sub color
  packages/outline/src/OutlineManager.ts
Labels: enhancement

#65 Delete stats
  README.md
  lerna.json
  package.json
  packages/auxiliary-lines/package.json
  packages/controls/package.json
  packages/framebuffer-picker/package.json
  packages/gizmo/package.json
  packages/lines/package.json
  packages/oasis-engine-toolkit/package.json
  packages/oasis-engine-toolkit/src/index.ts
  packages/outline/package.json
  packages/outline/src/OutlineManager.ts
  packages/planar-shadow-material/package.json
  packages/skeleton-viewer/package.json
  packages/stats/package.json
  packages/stats/src/Core.ts
  packages/stats/src/Monitor.ts
  packages/stats/src/Stats.ts
  packages/stats/src/hooks/DrawCallHook.ts
  packages/stats/src/hooks/ShaderHook.ts
  packages/stats/src/hooks/TextureHook.ts
  packages/stats/src/index.ts
  packages/stats/src/log.ts
  packages/stats/tsconfig.json
  tests/package.json
Labels: ignore for release
