Repository galacean/engine-toolkit, pull requests merged in 2022-07, with the labels that each got.

#20 Init gizmo
  packages/gizmo/package.json
  packages/gizmo/src/Axis.ts
  packages/gizmo/src/GizmoControls.ts
  packages/gizmo/src/Mesh.ts
  packages/gizmo/src/Rotate.ts
  packages/gizmo/src/Scale.ts
  packages/gizmo/src/Translate.ts
  packages/gizmo/src/Type.ts
  packages/gizmo/src/Utils.ts
  packages/gizmo/src/index.ts
  packages/gizmo/src/material.ts
  packages/gizmo/tsconfig.json
Labels: enhancement

#21 Modify the implementation of OrbitControl(Use InputManager)
  packages/controls/src/OrbitControl.ts
  packages/controls/src/Spherical.ts
  packages/controls/src/enums/ControlHandlerType.ts
  packages/controls/src/index.ts
  packages/controls/src/inputDevice/ControlKeyboard.ts
  packages/controls/src/inputDevice/ControlPointer.ts
  packages/controls/src/inputDevice/ControlWheel.ts
  packages/controls/src/inputDevice/IControlInput.ts
  packages/controls/src/inputDevice/StaticInterfaceImplement.ts
Labels: enhancement

#14 feat: planar shadow
  README.md
  packages/oasis-engine-toolkit/src/index.ts
  packages/planar-shadow-material/package.json
  packages/planar-shadow-material/src/PlanarShadowMaterial.ts
  packages/planar-shadow-material/src/index.ts
  packages/planar-shadow-material/tsconfig.json
Labels: enhancement

#24 Fix `Stats` automatic opening problem
  packages/stats/src/index.ts
Labels: ignore for release

#27 Refactor gizmo
  packages/gizmo/src/Axis.ts
  packages/gizmo/src/GizmoControls.ts
  packages/gizmo/src/Rotate.ts
  packages/gizmo/src/Scale.ts
  packages/gizmo/src/Translate.ts
  packages/gizmo/src/Type.ts
  packages/gizmo/src/Utils.ts
  packages/gizmo/src/index.ts
  packages/gizmo/src/material.ts
Labels: ignore for release

#26 Add `OutlineManager` to show outline of entities
  README.md
  packages/oasis-engine-toolkit/package.json
  packages/oasis-engine-toolkit/src/index.ts
  packages/outline/package.json
  packages/outline/src/OutlineManager.ts
  packages/outline/src/global.d.ts
  packages/outline/src/index.ts
  packages/outline/src/outline.fs.glsl
  packages/outline/src/outline.vs.glsl
  packages/outline/tsconfig.json
  packages/skeleton-viewer/package.json
  packages/skeleton-viewer/src/SkeletonViewer.ts
  packages/skeleton-viewer/src/index.ts
  packages/skeleton-viewer/tsconfig.json
Labels: enhancement

#28 feat: use replaceMaterial to render outline only
  packages/outline/src/OutlineManager.ts
Labels: bug, ignore for release

#31 Fix outline bug
  packages/outline/src/OutlineManager.ts
Labels: bug, ignore for release

#32 Fix WireFrameManager render bug by turn off vao in wireframe draw
  packages/auxiliary-lines/src/WireframeManager.ts
Labels: bug, ignore for release

#18 Add 2D Solid Line & Dash Line
  README.md
  package.json
  packages/lines/package.json
  packages/lines/src/global.d.ts
  packages/lines/src/index.ts
  packages/lines/src/line/DashLine.ts
  packages/lines/src/line/Line.ts
  packages/lines/src/line/constants.ts
  packages/lines/src/line/material/DashMaterial.ts
  packages/lines/src/line/material/LineMaterial.ts
  packages/lines/src/line/material/dashShader.ts
  packages/lines/src/line/material/lineShader.ts
  packages/lines/src/line/vertexBuilder/compile.sh
  packages/lines/src/line/vertexBuilder/index.ts
  packages/lines/src/line/vertexBuilder/line.c
  packages/lines/src/line/vertexBuilder/line.wasm
  packages/lines/tsconfig.json
  packages/oasis-engine-toolkit/package.json
  packages/oasis-engine-toolkit/src/index.ts
  rollup.config.js
Labels: enhancement

#33 fix: wireframe index buffer type bug
  packages/auxiliary-lines/src/WireframeManager.ts
  packages/auxiliary-lines/src/WireframePrimitive.ts
Labels: bug, ignore for release

#35 Fix outLine bug
  packages/outline/src/OutlineManager.ts
Labels: bug, ignore for release

#36 refactor: change api
  packages/framebuffer-picker/src/ColorRenderPass.ts
  packages/framebuffer-picker/src/FramebufferPicker.ts
Labels: bug, ignore for release

#38 fix spot light wireframe
  packages/auxiliary-lines/src/WireframeManager.ts
Labels: good first issue

#39 feat: rotate light to default forward direction
  packages/auxiliary-lines/src/WireframeManager.ts
Labels: bug, ignore for release

#37 Refactor gizmo control
  packages/gizmo/src/ArcLineMesh.ts
  packages/gizmo/src/Axis.ts
  packages/gizmo/src/CircleMesh.ts
  packages/gizmo/src/GizmoControls.ts
  packages/gizmo/src/LineMesh.ts
  packages/gizmo/src/Mesh.ts
  packages/gizmo/src/MeshMaterial.ts
  packages/gizmo/src/Rotate.ts
  packages/gizmo/src/Scale.ts
  packages/gizmo/src/Translate.ts
  packages/gizmo/src/Type.ts
  packages/gizmo/src/Utils.ts
  packages/gizmo/src/enums/GizmoState.ts
  packages/gizmo/src/index.ts
Labels: ignore for release

#41 Fix: change gizmo color & size
  packages/gizmo/src/Rotate.ts
  packages/gizmo/src/Translate.ts
  packages/gizmo/src/Utils.ts
Labels: bug, ignore for release

#43 fix: use pure outline color
  packages/outline/src/outline.fs.glsl
Labels: bug, ignore for release
