Repository galacean/engine-toolkit, pull requests merged in 2024-07, with the labels that each got.

#284 Feat: adjust axis alpha according to scene camera angle
  packages/gizmo/src/Axis.ts
  packages/gizmo/src/Gizmo.ts
  packages/gizmo/src/Rotate.ts
  packages/gizmo/src/Scale.ts
  packages/gizmo/src/Translate.ts
  packages/gizmo/src/Type.ts
  packages/gizmo/src/Utils.ts
Labels: enhancement

#283 Fix: Gizmo hover highlight
  packages/gizmo/src/Gizmo.ts
  packages/gizmo/src/Rotate.ts
  packages/gizmo/src/Scale.ts
  packages/gizmo/src/Translate.ts
Labels: enhancement

#285 fix: Optimize Gizmo Axis Fade Algorithm
  packages/gizmo/src/Gizmo.ts
Labels: bug

#286 Enhancement Shader API
  packages/shaderlab/src/shaders/shadingPBR/LightIndirectPBR.glsl
  packages/shaderlab/src/shaders/shadingPBR/LightProbe.glsl
  packages/shaderlab/src/shaders/shadingPBR/index.ts
Labels: enhancement

#280 Advanced Shader
  packages/custom-material/src/advanced-shader/eye/Eye.gs
  packages/custom-material/src/advanced-shader/eye/EyeForwardPass.glsl
  packages/custom-material/src/advanced-shader/eye/EyeFunction.glsl
  packages/custom-material/src/advanced-shader/hair/Hair.gs
  packages/custom-material/src/advanced-shader/hair/HairForwardPass.glsl
  packages/custom-material/src/advanced-shader/hair/HairFunction.glsl
  packages/custom-material/src/advanced-shader/hair/HairLightDirect.glsl
  packages/custom-material/src/advanced-shader/sss/SSS.gs
  packages/custom-material/src/advanced-shader/sss/SSSForwardPass.glsl
  packages/custom-material/src/advanced-shader/sss/SSSFunction.glsl
  packages/custom-material/src/advanced-shader/sss/SSSLightDirect.glsl
  packages/custom-material/src/advanced-shader/thinfilm/IridescenceForwardPass.glsl
  packages/custom-material/src/advanced-shader/thinfilm/IridescenceFunction.glsl
  packages/custom-material/src/advanced-shader/thinfilm/IridescenceIndirectLight.glsl
  packages/custom-material/src/advanced-shader/thinfilm/IridescencedirectLight.glsl
  packages/custom-material/src/advanced-shader/thinfilm/Iridescene.gs
Labels: enhancement, shader

#287 Fix surfaceData not set f0
  packages/custom-material/src/advanced-shader/eye/EyeForwardPass.glsl
  packages/custom-material/src/advanced-shader/hair/HairForwardPass.glsl
  packages/custom-material/src/advanced-shader/sss/SSSForwardPass.glsl
  packages/custom-material/src/advanced-shader/thinfilm/IridescenceForwardPass.glsl
Labels: bug

#291 Add XR Tool for Galacean Editor
  packages/xr/README.md
  packages/xr/package.json
  packages/xr/src/component/TrackedComponent.ts
  packages/xr/src/component/XROrigin.ts
  packages/xr/src/index.ts
  packages/xr/src/trackable/XRAnchorManager.ts
  packages/xr/src/trackable/XRImageManager.ts
  packages/xr/src/trackable/XRPlaneManager.ts
  packages/xr/src/trackable/XRTrackedObjectManager.ts
  packages/xr/tsconfig.json
  rollup.config.mjs
  rollup.miniprogram.plugin.mjs
Labels: feature

#296 Fix: sprite disable batching when pick
  packages/framebuffer-picker/src/FramebufferPicker.ts
Labels: enhancement
